version: "3"
services:
  random:
    build: ./docker/random
    restart: always
    ports:
      - "5000:5000"

  csv:
    build: ./docker/csv
    environment:
      - RANDOM_GENERATOR_HOST=random
      - RANDOM_GENERATOR_PORT=5000
    restart: always
    ports:
      - "5001:5001"
